### ISSUE TITLE
iOS 8 Compatibility?

### ISSUE THREAD

**Issue by mr-gosh** [DiOS-Analysis/DiOS#3]
DiOS didn't work out of the box with an jailbroken iOS8 Device.
Is this a known Problem or should DiOS work with jailbroken iOS8 Devices?

**Comment by artemk** [comment]
@awein Do you think it will be implemented soon?

**Comment by Morrandir** [comment]
I was able to modify my copy of the code to run it on iOS 8.

Basically the UI hierarchy of the Apple ID alert changed, you need to modify the code to locate the password box.

And some of the APIs changed slightly in SBApplicationController.h header file.
`applicationWithDisplayIdentifier:arg1` has been renamed to `applicationWithBundleIdentifier:arg1`
`initWithApplication:arg1` seems to have also been changed, now I must call it in the main thread.

The other thing I came across is since I'm using an iPhone 6+, I compiled the dylibs under arm64 architecture. But seems some applications in the App Store is still 32 bit so they need to load 32 bit BasicAnalyzer.dylib. Ideally I think we should compile BasicAnalyzer.dylib for both 32 bit and 64 bit archs, but I cannot get this done using DHowett's theos. I tried with rpetrich's theos but still no success. In the end I had to compile it for 32 bit and 64 bit archs separately and then use lipo to merge them.

Except for those changes seems everything else is still working correctly.

**Comment by artemk** [comment]
@Morrandir can you please push your changes into fork?

**Comment by awein** [comment]
fixed with https://github.com/DiOS-Analysis/Pilot/commit/ed1b75eeca724c949499674098989e0c64ef58c4

**Comment by artemk** [comment]
@awein so Pilot is compatible with ios8 ?
